name: Build and Test
on:
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      #  - name: docker login
      #    run: docker login
      - name: Build
        run: docker build -t ayush4web/react-cicd -f Dockerfile.dev .

      - name: Test React
        run : docker run -e CI=true ayush4web/react-cicd npm run test  
